#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='stickstoff'


SOURCE_FILES=  [
				'stickstoff.c',
				'stickstoff_util.c',
				'stickstoff_register_modul.c',			
				'denit.c',
				'miner.c',
				'hydro.c',
				'stickstoff_load.c'
                ]

     
def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_STD,                
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_STD,
                install_path    = bld.env.INSTALL_MODELS
                )
