python waf configure build install --prefix="C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built"  --USE_OPENMP --max_optimize --check-c-compiler=gcc --check-cxx-compiler=g++ --GUI
move "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\bin\expertn_bin.exe" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\bin\expertn_gui.exe"
python waf configure build install --prefix="C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built"  --USE_OPENMP --max_optimize --check-c-compiler=gcc --check-cxx-compiler=g++
move "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\bin\expertn_bin.exe" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\bin\expertn_terminal.exe"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\lib"
move "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\bin\*.a" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\lib"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\xpn"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\xpn\libexpertn_class"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\xpn\libexpertn_class\include"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\dev\xpn\libexpertn_class\include\*.h" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\xpn\libexpertn_class\include"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\xpn\libexpertn_modul_base"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\xpn\libexpertn_modul_base\include"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\dev\xpn\libexpertn_modul_base\include\*.h" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\dev\xpn\libexpertn_modul_base\include"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\cfg"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\cfg_system"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built\cfg_system\*" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\cfg_system"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\cfg_template"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built\cfg_template\*" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\cfg_template"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\doc"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built\doc\*" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\built\doc"

REM Expert-N Tools:
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\expertn_tools"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\expertn_tools\noah_soils"
mkdir "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\expertn_tools\template"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\expertn_tools\*.*" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\expertn_tools"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\expertn_tools\noah_soils\*.*" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\expertn_tools\noah_soils"
copy "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\expertn_tools\template\*.*" "C:\Documents and Settings\Christian Klein\My Documents\projects\expertn50\built_new\expertn_tools\template"
