#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='evapotranspiration_pm'


SOURCE_FILES=  [
                 'evapotranspiration.c',
                 'evapotranspiration_fao.c',
                 'evapotranspiration_haude.c',
                 'surface.c',
                 'evapotranspiration_pm_register_modul.c',
                 'kc_factor.c'
                ]


def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_STD,
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_STD,
                install_path    = bld.env.INSTALL_MODELS
                )
