#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='surface_layer'


SOURCE_FILES=  [
				'surface_layer.c',
				'surface_layer_register_modul.c'
                ]

     
def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_STD,                
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_STD,
                install_path    = bld.env.INSTALL_MODELS
                )
