#define INTERCEPTION_REG \
xpn_register_var_add_pdouble(var_list,"interception.Bal_I",&(self->Bal_I),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Bal_E",&(self->Bal_E),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Bal_T",&(self->Bal_T),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Bal_R",&(self->Bal_R),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Bal_D",&(self->Bal_D),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Epot_Yr",&(self->Epot_Yr),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Eact_Yr",&(self->Eact_Yr),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.PreciRate_Yr",&(self->PreciRate_Yr),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.FreeThroughfall_Yr",&(self->FreeThroughfall_Yr),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Throughfall_Yr",&(self->Throughfall_Yr),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.PreciRate_Day",&(self->PreciRate_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Epot_Day",&(self->Epot_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Eact_Day",&(self->Eact_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyInput_Day",&(self->CanopyInput_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.FreeThroughfall_Day",&(self->FreeThroughfall_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyWat_Day",&(self->CanopyWat_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyWat_Day_old",&(self->CanopyWat_Day_old),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Drainage_Day",&(self->Drainage_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Interception_Day",&(self->Interception_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Throughfall_Day",&(self->Throughfall_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.PreciRate_dt",&(self->PreciRate_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Epot_dt",&(self->Epot_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Eact_dt",&(self->Eact_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyInput_dt",&(self->CanopyInput_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.FreeThroughfall_dt",&(self->FreeThroughfall_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyWat_dt",&(self->CanopyWat_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.C_S_dt",&(self->C_S_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyWat_dt_old",&(self->CanopyWat_dt_old),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Drainage_dt",&(self->Drainage_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Drainage_dt2",&(self->Drainage_dt2),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Interception_dt",&(self->Interception_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Throughfall_dt",&(self->Throughfall_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Epot_R",&(self->Epot_R),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Eact_R",&(self->Eact_R),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyInputR",&(self->CanopyInputR),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.FreeThroughfallR",&(self->FreeThroughfallR),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyWatR",&(self->CanopyWatR),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.CanopyWatR_old",&(self->CanopyWatR_old),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.DrainageR",&(self->DrainageR),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.InterceptionR",&(self->InterceptionR),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.ThroughfallR",&(self->ThroughfallR),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.SaturationCap",&(self->SaturationCap),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.elevation",&(self->elevation),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.T",&(self->T),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.RH",&(self->RH),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.ea",&(self->ea),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.es",&(self->es),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.omega",&(self->omega),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Ra_h",&(self->Ra_h),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Ra_d",&(self->Ra_d),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Ra_hDay",&(self->Ra_hDay),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.RaDay",&(self->RaDay),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Rs",&(self->Rs),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.RsDay",&(self->RsDay),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Rs0",&(self->Rs0),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Rn",&(self->Rn),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.RnDay",&(self->RnDay),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Rns",&(self->Rns),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.Rnl",&(self->Rnl),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.SI_R",&(self->SI_R),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.SI_dt",&(self->SI_dt),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.SI_Day",&(self->SI_Day),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.SI_Yr",&(self->SI_Yr),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"interception.SImax",&(self->SImax),-1,TRUE,TRUE); \
xpn_register_var_add_pdouble(var_list,"output.Water.interception.Rn",&(self->Rn),-1,TRUE,TRUE);

