#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='daisy'


SOURCE_FILES=  [
                 'albedo.c',
                 'albedo_ceres.c',
                 'daisy.c',
                 'daisy_register_modul.c'                 
                ]

        
def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_CLASS,                
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_CLASS,
                install_path    = bld.env.INSTALL_MODELS
                )
