#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='expertn_database'


SOURCE_FILES=  [
                 'database_help_func.c',
                 'expertn_database.c',
                 'expertn_database_register.c',
                 'expertn_standard_ini.c'
                ]


def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_CLASS,
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_CLASS,
                install_path    = bld.env.INSTALL_MODELS
                )
