#define XCHEMIST_REG \
\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3N,"pCh.pCLayer.fNO3N",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3NAds,"pCh.pCLayer.fNO3NAds",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4N,"pCh.pCLayer.fNH4N",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NAds,"pCh.pCLayer.fNH4NAds",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NGas,"pCh.pCLayer.fNH4NGas",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaN,"pCh.pCLayer.fUreaN",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNAds,"pCh.pCLayer.fUreaNAds",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOC,"pCh.pCLayer.fDOC",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCAds,"pCh.pCLayer.fDOCAds",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDON,"pCh.pCLayer.fDON",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONAds,"pCh.pCLayer.fDONAds",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOMCN,"pCh.pCLayer.fDOMCN",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4Manure,"pCh.pCLayer.fNH4Manure",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNManure,"pCh.pCLayer.fNManure",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCManure,"pCh.pCLayer.fCManure",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fManureCN,"pCh.pCLayer.fManureCN",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNLitter,"pCh.pCLayer.fNLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCLitter,"pCh.pCLayer.fCLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fLitterCN,"pCh.pCLayer.fLitterCN",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ON,"pCh.pCLayer.fN2ON",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ONGasConc,"pCh.pCLayer.fN2ONGasConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ONGasConcOld,"pCh.pCLayer.fN2ONGasConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2N,"pCh.pCLayer.fN2N",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2NGasConc,"pCh.pCLayer.fN2NGasConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2NGasConcOld,"pCh.pCLayer.fN2NGasConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNON,"pCh.pCLayer.fNON",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNONGasConc,"pCh.pCLayer.fNONGasConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNONGasConcOld,"pCh.pCLayer.fNONGasConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCO2C,"pCh.pCLayer.fCO2C",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCsolC,"pCh.pCLayer.fCsolC",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNsolC,"pCh.pCLayer.fNsolC",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCFreeFOM,"pCh.pCLayer.fCFreeFOM",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCFreeHumus,"pCh.pCLayer.fCFreeHumus",0.0);\
xpn_register_var_init_array(xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,afNOrgFOMFrac[i],varname,0.0),"pCh.pCLayer.afNOrgFOMFrac",3) \
xpn_register_var_init_array(xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,afCOrgFOMFrac[i],varname,0.0),"pCh.pCLayer.afCOrgFOMFrac",3) \
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNFOMVeryFast,"pCh.pCLayer.fNFOMVeryFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCFOMVeryFast,"pCh.pCLayer.fCFOMVeryFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNFOMFast,"pCh.pCLayer.fNFOMFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCFOMFast,"pCh.pCLayer.fCFOMFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNFOMSlow,"pCh.pCLayer.fNFOMSlow",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCFOMSlow,"pCh.pCLayer.fCFOMSlow",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNMicBiomFast,"pCh.pCLayer.fNMicBiomFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCMicBiomFast,"pCh.pCLayer.fCMicBiomFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNMicBiomSlow,"pCh.pCLayer.fNMicBiomSlow",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCMicBiomSlow,"pCh.pCLayer.fCMicBiomSlow",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNMicBiomDenit,"pCh.pCLayer.fNMicBiomDenit",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCMicBiomDenit,"pCh.pCLayer.fCMicBiomDenit",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNHumusFast,"pCh.pCLayer.fNHumusFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCHumusFast,"pCh.pCLayer.fCHumusFast",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNHumusSlow,"pCh.pCLayer.fNHumusSlow",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCHumusSlow,"pCh.pCLayer.fCHumusSlow",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNHumusStable,"pCh.pCLayer.fNHumusStable",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCHumusStable,"pCh.pCLayer.fCHumusStable",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNStrcLitter,"pCh.pCLayer.fNStrcLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCStrcLitter,"pCh.pCLayer.fCStrcLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fLignFracStrcLit,"pCh.pCLayer.fLignFracStrcLit",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNMtbLitter,"pCh.pCLayer.fNMtbLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCMtbLitter,"pCh.pCLayer.fCMtbLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNGrossRootLitter,"pCh.pCLayer.fNGrossRootLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCGrossRootLitter,"pCh.pCLayer.fCGrossRootLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCNGrossRootLitter,"pCh.pCLayer.fCNGrossRootLitter",30.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNFineRootLitter,"pCh.pCLayer.fNFineRootLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCFineRootLitter,"pCh.pCLayer.fCFineRootLitter",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCNFineRootLitter,"pCh.pCLayer.fCNFineRootLitter",30.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fChemX,"pCh.pCLayer.fChemX",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3Nmgkg,"pCh.pCLayer.fNO3Nmgkg",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4Nmgkg,"pCh.pCLayer.fNH4Nmgkg",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNmgkg,"pCh.pCLayer.fUreaNmgkg",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fChemXmgkg,"pCh.pCLayer.fChemXmgkg",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3NSoilConc,"pCh.pCLayer.fNO3NSoilConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3NAdsConc,"pCh.pCLayer.fNO3NAdsConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NSoilConc,"pCh.pCLayer.fNH4NSoilConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NAdsConc,"pCh.pCLayer.fNH4NAdsConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NGasConc,"pCh.pCLayer.fNH4NGasConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNSoilConc,"pCh.pCLayer.fUreaNSoilConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNAdsConc,"pCh.pCLayer.fUreaNAdsConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNGasConc,"pCh.pCLayer.fUreaNGasConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCSoilConc,"pCh.pCLayer.fDOCSoilConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCAdsConc,"pCh.pCLayer.fDOCAdsConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONSoilConc,"pCh.pCLayer.fDONSoilConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONAdsConc,"pCh.pCLayer.fDONAdsConc",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3NSoilConcOld,"pCh.pCLayer.fNO3NSoilConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3NAdsConcOld,"pCh.pCLayer.fNO3NAdsConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NSoilConcOld,"pCh.pCLayer.fNH4NSoilConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NAdsConcOld,"pCh.pCLayer.fNH4NAdsConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NGasConcOld,"pCh.pCLayer.fNH4NGasConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNSoilConcOld,"pCh.pCLayer.fUreaNSoilConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNAdsConcOld,"pCh.pCLayer.fUreaNAdsConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNGasConcOld,"pCh.pCLayer.fUreaNGasConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCSoilConcOld,"pCh.pCLayer.fDOCSoilConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCAdsConcOld,"pCh.pCLayer.fDOCAdsConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONSoilConcOld,"pCh.pCLayer.fDONSoilConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONAdsConcOld,"pCh.pCLayer.fDONAdsConcOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCSltConcMob,"pCh.pCLayer.fDOCSltConcMob",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCSltConcImm,"pCh.pCLayer.fDOCSltConcImm",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCAdsConcMob,"pCh.pCLayer.fDOCAdsConcMob",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCAdsConcImm,"pCh.pCLayer.fDOCAdsConcImm",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCSltConcMobOld,"pCh.pCLayer.fDOCSltConcMobOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCSltConcImmOld,"pCh.pCLayer.fDOCSltConcImmOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCAdsConcMobOld,"pCh.pCLayer.fDOCAdsConcMobOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDOCAdsConcImmOld,"pCh.pCLayer.fDOCAdsConcImmOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3DenitMaxR,"pCh.pCLayer.fNO3DenitMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ODenitMaxR,"pCh.pCLayer.fN2ODenitMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NitrMaxR,"pCh.pCLayer.fNH4NitrMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaHydroMaxR,"pCh.pCLayer.fUreaHydroMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fLitterMinerMaxR,"pCh.pCLayer.fLitterMinerMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fManureMinerMaxR,"pCh.pCLayer.fManureMinerMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fHumusMinerMaxR,"pCh.pCLayer.fHumusMinerMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fHumusToDONMaxR,"pCh.pCLayer.fHumusToDONMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fLitterToDONMaxR,"pCh.pCLayer.fLitterToDONMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fManureToDONMaxR,"pCh.pCLayer.fManureToDONMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONToHumusMaxR,"pCh.pCLayer.fDONToHumusMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONToLitterMaxR,"pCh.pCLayer.fDONToLitterMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONMinerMaxR,"pCh.pCLayer.fDONMinerMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3DenitR,"pCh.pCLayer.fNO3DenitR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ODenitR,"pCh.pCLayer.fN2ODenitR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NitrR,"pCh.pCLayer.fNH4NitrR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaHydroR,"pCh.pCLayer.fUreaHydroR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fMinerR,"pCh.pCLayer.fMinerR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fLitterMinerR,"pCh.pCLayer.fLitterMinerR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fManureMinerR,"pCh.pCLayer.fManureMinerR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fHumusMinerR,"pCh.pCLayer.fHumusMinerR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fHumusToDONR,"pCh.pCLayer.fHumusToDONR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fLitterToDONR,"pCh.pCLayer.fLitterToDONR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fManureToDONR,"pCh.pCLayer.fManureToDONR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONToHumusR,"pCh.pCLayer.fDONToHumusR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONToLitterR,"pCh.pCLayer.fDONToLitterR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fDONMinerR,"pCh.pCLayer.fDONMinerR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fFOMVeryFastDecMaxR,"pCh.pCLayer.fFOMVeryFastDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fFOMFastDecMaxR,"pCh.pCLayer.fFOMFastDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fFOMSlowDecMaxR,"pCh.pCLayer.fFOMSlowDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fMicBiomFastDecMaxR,"pCh.pCLayer.fMicBiomFastDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fMicBiomSlowDecMaxR,"pCh.pCLayer.fMicBiomSlowDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fBioMFastNonlinDecMaxR,"pCh.pCLayer.fBioMFastNonlinDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fBioMSlowNonlinDecMaxR,"pCh.pCLayer.fBioMSlowNonlinDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fHumusFastMaxDecMaxR,"pCh.pCLayer.fHumusFastMaxDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fHumusSlowMaxDecMaxR,"pCh.pCLayer.fHumusSlowMaxDecMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaNVolatR,"pCh.pCLayer.fUreaNVolatR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4VolatR,"pCh.pCLayer.fNH4VolatR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3VolatR,"pCh.pCLayer.fNO3VolatR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNImmobR,"pCh.pCLayer.fNImmobR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNLitterImmobR,"pCh.pCLayer.fNLitterImmobR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNManureImmobR,"pCh.pCLayer.fNManureImmobR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNHumusImmobR,"pCh.pCLayer.fNHumusImmobR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCO2ProdR,"pCh.pCLayer.fCO2ProdR",0.0);\
xpn_register_var_init_array(xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,afFOMDecR[i],varname,0.0),"pCh.pCLayer.afFOMDecR",3) \
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fHumusDecR,"pCh.pCLayer.fHumusDecR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3DenitDay,"pCh.pCLayer.fNO3DenitDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ODenitDay,"pCh.pCLayer.fN2ODenitDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NitrDay,"pCh.pCLayer.fNH4NitrDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNImmobDay,"pCh.pCLayer.fNImmobDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaHydroDay,"pCh.pCLayer.fUreaHydroDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNManureMinerDay,"pCh.pCLayer.fNManureMinerDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNLitterMinerDay,"pCh.pCLayer.fNLitterMinerDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNHumusMinerDay,"pCh.pCLayer.fNHumusMinerDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCManureMinerDay,"pCh.pCLayer.fCManureMinerDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCLitterMinerDay,"pCh.pCLayer.fCLitterMinerDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCHumusMinerDay,"pCh.pCLayer.fCHumusMinerDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCO2ProdDay,"pCh.pCLayer.fCO2ProdDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaLeachDay,"pCh.pCLayer.fUreaLeachDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4LeachDay,"pCh.pCLayer.fNH4LeachDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3LeachDay,"pCh.pCLayer.fNO3LeachDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaVolatDay,"pCh.pCLayer.fUreaVolatDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4VolatDay,"pCh.pCLayer.fNH4VolatDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3VolatDay,"pCh.pCLayer.fNO3VolatDay",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNO3DenitCum,"pCh.pCLayer.fNO3DenitCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ODenitCum,"pCh.pCLayer.fN2ODenitCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NitrCum,"pCh.pCLayer.fNH4NitrCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNImmobCum,"pCh.pCLayer.fNImmobCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fUreaHydroCum,"pCh.pCLayer.fUreaHydroCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNManureMinerCum,"pCh.pCLayer.fNManureMinerCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNLitterMinerCum,"pCh.pCLayer.fNLitterMinerCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNHumusMinerCum,"pCh.pCLayer.fNHumusMinerCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCManureMinerCum,"pCh.pCLayer.fCManureMinerCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCLitterMinerCum,"pCh.pCLayer.fCLitterMinerCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCHumusMinerCum,"pCh.pCLayer.fCHumusMinerCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCO2ProdCum,"pCh.pCLayer.fCO2ProdCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNAnorg,"pCh.pCLayer.fNAnorg",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4NitrCoeff,"pCh.pCLayer.fNH4NitrCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCNCoeff,"pCh.pCLayer.fCNCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fH2ONitrCoeff,"pCh.pCLayer.fH2ONitrCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fpHCoeff,"pCh.pCLayer.fpHCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fTempCoeff,"pCh.pCLayer.fTempCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fTempCoeffOld,"pCh.pCLayer.fTempCoeffOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fGasDiffCoef,"pCh.pCLayer.fGasDiffCoef",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fLiqDiffCoef,"pCh.pCLayer.fLiqDiffCoef",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fH2ONitrCoeff_2,"pCh.pCLayer.fH2ONitrCoeff_2",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fPpmTOkg,"pCh.pCLayer.fPpmTOkg",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4ToN2OR,"pCh.pCLayer.fNH4ToN2OR",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNH4ToN2OCum,"pCh.pCLayer.fNH4ToN2OCum",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fMicBiomCN,"pCh.pCLayer.fMicBiomCN",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ONGasFlux,"pCh.pCLayer.fN2ONGasFlux",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2ONGasFluxOld,"pCh.pCLayer.fN2ONGasFluxOld",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fGasDiffusiv,"pCh.pCLayer.fGasDiffusiv",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fN2OKh,"pCh.pCLayer.fN2OKh",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fCSoilMicBiom,"pCh.pCLayer.fCSoilMicBiom",0.0);\
xpn_register_var_init_rec_struct( var_list,CLAYER, pCh->pCLayer,xpn_register_var_init_pdouble,fNSoilMicBiom,"pCh.pCLayer.fNSoilMicBiom",0.0);\
\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNO3NSurf,"pCh.pCProfile.fNO3NSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH4NSurf,"pCh.pCProfile.fNH4NSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fUreaNSurf,"pCh.pCProfile.fUreaNSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDOCSurf,"pCh.pCProfile.fDOCSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDONSurf,"pCh.pCProfile.fDONSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNDOMSurf,"pCh.pCProfile.fCNDOMSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDryMatterLitterSurf,"pCh.pCProfile.fDryMatterLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNLitterSurf,"pCh.pCProfile.fNLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCLitterSurf,"pCh.pCProfile.fCLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNLitterSurf,"pCh.pCProfile.fCNLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDryMatterManureSurf,"pCh.pCProfile.fDryMatterManureSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH4ManureSurf,"pCh.pCProfile.fNH4ManureSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNManureSurf,"pCh.pCProfile.fNManureSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCManureSurf,"pCh.pCProfile.fCManureSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNManureSurf,"pCh.pCProfile.fCNManureSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDryMatterHumusSurf,"pCh.pCProfile.fDryMatterHumusSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCHumusSurf,"pCh.pCProfile.fCHumusSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNHumusSurf,"pCh.pCProfile.fNHumusSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNHumusSurf,"pCh.pCProfile.fCNHumusSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCStandCropRes,"pCh.pCProfile.fCStandCropRes",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNStandCropRes,"pCh.pCProfile.fNStandCropRes",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCStrLitterSurf,"pCh.pCProfile.fCStrLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNStrLitterSurf,"pCh.pCProfile.fNStrLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fLignFracStrLitSurf,"pCh.pCProfile.fLignFracStrLitSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCMtbLitterSurf,"pCh.pCProfile.fCMtbLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNMtbLitterSurf,"pCh.pCProfile.fNMtbLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCMicLitterSurf,"pCh.pCProfile.fCMicLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNMicLitterSurf,"pCh.pCProfile.fNMicLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCLeafLitterSurf,"pCh.pCProfile.fCLeafLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNLeafLitterSurf,"pCh.pCProfile.fNLeafLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNLeafLitterSurf,"pCh.pCProfile.fCNLeafLitterSurf",30.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCBranchLitterSurf,"pCh.pCProfile.fCBranchLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNBranchLitterSurf,"pCh.pCProfile.fNBranchLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNBranchLitterSurf,"pCh.pCProfile.fCNBranchLitterSurf",30.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCStemLitterSurf,"pCh.pCProfile.fCStemLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNStemLitterSurf,"pCh.pCProfile.fNStemLitterSurf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNStemLitterSurf,"pCh.pCProfile.fCNStemLitterSurf",30.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCLitter,"pCh.pCProfile.fCLitter",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNLitter,"pCh.pCProfile.fNLitter",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNLitter,"pCh.pCProfile.fCNLitter",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCManure,"pCh.pCProfile.fCManure",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNManure,"pCh.pCProfile.fNManure",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNManure,"pCh.pCProfile.fCNManure",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCHumus,"pCh.pCProfile.fCHumus",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNHumus,"pCh.pCProfile.fNHumus",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNHumus,"pCh.pCProfile.fCNHumus",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDON,"pCh.pCProfile.fDON",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDOC,"pCh.pCProfile.fDOC",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCSoilMicBiom,"pCh.pCProfile.fCSoilMicBiom",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNSoilMicBiom,"pCh.pCProfile.fNSoilMicBiom",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCNSoilMicBiom,"pCh.pCProfile.fCNSoilMicBiom",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fLigFracLeaf,"pCh.pCProfile.fLigFracLeaf",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fLigFracBranch,"pCh.pCProfile.fLigFracBranch",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fLigFracStem,"pCh.pCProfile.fLigFracStem",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fLigFracFineRoot,"pCh.pCProfile.fLigFracFineRoot",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fLigFracCoarseRoot,"pCh.pCProfile.fLigFracCoarseRoot",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fFineBranchDecR,"pCh.pCProfile.fFineBranchDecR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fLargeWoodDecR,"pCh.pCProfile.fLargeWoodDecR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCoarseRootDecR,"pCh.pCProfile.fCoarseRootDecR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNLitterMinerDay,"pCh.pCProfile.fNLitterMinerDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNManureMinerDay,"pCh.pCProfile.fNManureMinerDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNHumusMinerDay,"pCh.pCProfile.fNHumusMinerDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNMinerDay,"pCh.pCProfile.fNMinerDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCO2ProdDay,"pCh.pCProfile.fCO2ProdDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNLitterImmobDay,"pCh.pCProfile.fNLitterImmobDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNManureImmobDay,"pCh.pCProfile.fNManureImmobDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNHumusImmobDay,"pCh.pCProfile.fNHumusImmobDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNImmobDay,"pCh.pCProfile.fNImmobDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fUreaHydroDay,"pCh.pCProfile.fUreaHydroDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH4NitrDay,"pCh.pCProfile.fNH4NitrDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH4ToN2ODay,"pCh.pCProfile.fNH4ToN2ODay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNO3DenitDay,"pCh.pCProfile.fNO3DenitDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fN2ODenitDay,"pCh.pCProfile.fN2ODenitDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fN2OEmisDay,"pCh.pCProfile.fN2OEmisDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNOEmisDay,"pCh.pCProfile.fNOEmisDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fN2EmisDay,"pCh.pCProfile.fN2EmisDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH3VolatDay,"pCh.pCProfile.fNH3VolatDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCO2EmisDay,"pCh.pCProfile.fCO2EmisDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCO2SurfEmisDay,"pCh.pCProfile.fCO2SurfEmisDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNO3NImisR,"pCh.pCProfile.fNO3NImisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fUreaLeachDay,"pCh.pCProfile.fUreaLeachDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH4LeachDay,"pCh.pCProfile.fNH4LeachDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNO3LeachDay,"pCh.pCProfile.fNO3LeachDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fN2ODrainDay,"pCh.pCProfile.fN2ODrainDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNTotalLeachDay,"pCh.pCProfile.fNTotalLeachDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDONLeachDay,"pCh.pCProfile.fDONLeachDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fDOCLeachDay,"pCh.pCProfile.fDOCLeachDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNUptakeDay,"pCh.pCProfile.fNUptakeDay",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNLitterMinerCum,"pCh.pCProfile.dNLitterMinerCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNManureMinerCum,"pCh.pCProfile.dNManureMinerCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNHumusMinerCum,"pCh.pCProfile.dNHumusMinerCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNMinerCum,"pCh.pCProfile.dNMinerCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNLitterImmobCum,"pCh.pCProfile.dNLitterImmobCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNManureImmobCum,"pCh.pCProfile.dNManureImmobCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNHumusImmobCum,"pCh.pCProfile.dNHumusImmobCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNImmobCum,"pCh.pCProfile.dNImmobCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNetNMinerCum30,"pCh.pCProfile.dNetNMinerCum30",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dCMinerCum,"pCh.pCProfile.dCMinerCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dCO2ProdCum,"pCh.pCProfile.dCO2ProdCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dUreaHydroCum,"pCh.pCProfile.dUreaHydroCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNH4NitrCum,"pCh.pCProfile.dNH4NitrCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNH4ToN2OCum,"pCh.pCProfile.dNH4ToN2OCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNO3DenitCum,"pCh.pCProfile.dNO3DenitCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dN2ODenitCum,"pCh.pCProfile.dN2ODenitCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dN2OEmisCum,"pCh.pCProfile.dN2OEmisCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNOEmisCum,"pCh.pCProfile.dNOEmisCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNEmisCum,"pCh.pCProfile.dNEmisCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dN2EmisCum,"pCh.pCProfile.dN2EmisCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNH3VolatCum,"pCh.pCProfile.dNH3VolatCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dCO2EmisCum,"pCh.pCProfile.dCO2EmisCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dCO2EmisCumSum,"pCh.pCProfile.dCO2EmisCumSum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dCO2SurfEmisCum,"pCh.pCProfile.dCO2SurfEmisCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dCH4ImisCum,"pCh.pCProfile.dCH4ImisCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dN2ODrainCum,"pCh.pCProfile.dN2ODrainCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dUreaLeachCum,"pCh.pCProfile.dUreaLeachCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNH4LeachCum,"pCh.pCProfile.dNH4LeachCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNO3LeachCum,"pCh.pCProfile.dNO3LeachCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNTotalLeachCum,"pCh.pCProfile.dNTotalLeachCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dDONLeachCum,"pCh.pCProfile.dDONLeachCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dDOCLeachCum,"pCh.pCProfile.dDOCLeachCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->dNUptakeCum,"pCh.pCProfile.dNUptakeCum",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCO2EmisR,"pCh.pCProfile.fCO2EmisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCO2SurfEmisR,"pCh.pCProfile.fCO2SurfEmisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fCH4ImisR,"pCh.pCProfile.fCH4ImisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH4NImisR,"pCh.pCProfile.fNH4NImisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNO3LeachR,"pCh.pCProfile.fNO3LeachR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fN2OEmisR,"pCh.pCProfile.fN2OEmisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNOEmisR,"pCh.pCProfile.fNOEmisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fN2EmisR,"pCh.pCProfile.fN2EmisR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNFertilizerR,"pCh.pCProfile.fNFertilizerR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH3VolatR,"pCh.pCProfile.fNH3VolatR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH3VolatMaxR,"pCh.pCProfile.fNH3VolatMaxR",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fNH4ToN2OR,"pCh.pCProfile.fNH4ToN2OR",0.0);\
\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMolDiffCoef,"pCh.pCParam.fMolDiffCoef",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMinerEffFac,"pCh.pCParam.fMinerEffFac",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMinerHumFac,"pCh.pCParam.fMinerHumFac",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fBioMassFastCN,"pCh.pCParam.fBioMassFastCN",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fBioMassSlowCN,"pCh.pCParam.fBioMassSlowCN",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fBioMassDenitCN,"pCh.pCParam.fBioMassDenitCN",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMinerSatActiv,"pCh.pCParam.fMinerSatActiv",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMinerTempB,"pCh.pCParam.fMinerTempB",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMinerQ10,"pCh.pCParam.fMinerQ10",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMinerThetaMin,"pCh.pCParam.fMinerThetaMin",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitThetaMin,"pCh.pCParam.fDenitThetaMin",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitKsNO3,"pCh.pCParam.fDenitKsNO3",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitKsCsol,"pCh.pCParam.fDenitKsCsol",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMaintCoeff,"pCh.pCParam.fMaintCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitMaintCoeff,"pCh.pCParam.fDenitMaintCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fYieldCoeff,"pCh.pCParam.fYieldCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitYieldCoeff,"pCh.pCParam.fDenitYieldCoeff",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fBioFastMaxGrowR,"pCh.pCParam.fBioFastMaxGrowR",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fBioSlowMaxGrowR,"pCh.pCParam.fBioSlowMaxGrowR",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitMaxGrowR,"pCh.pCParam.fDenitMaxGrowR",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDispersivity,"pCh.pCParam.fDispersivity",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fNitrifPot,"pCh.pCParam.fNitrifPot",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fNitrifNO3NH4Ratio,"pCh.pCParam.fNitrifNO3NH4Ratio",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fNitrifNH4ToN2O,"pCh.pCParam.fNitrifNH4ToN2O",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fN2ORedMaxR,"pCh.pCParam.fN2ORedMaxR",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitReWet,"pCh.pCParam.fDenitReWet",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitFreeze,"pCh.pCParam.fDenitFreeze",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fDenitThaw,"pCh.pCParam.fDenitThaw",0.0);\
xpn_register_var_init_array(xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,afKd[i],varname,0.0),"pCh.pCParam.afKd",6) \
xpn_register_var_init_array(xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,afKh[i],varname,0.0),"pCh.pCParam.afKh",6) \
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMobImmSltEC,"pCh.pCParam.fMobImmSltEC",0.0);\
xpn_register_var_init_rec_struct( var_list,CPARAM, pCh->pCParam,xpn_register_var_init_pdouble,fMobAdsSiteFrac,"pCh.pCParam.fMobAdsSiteFrac",0.0);\
\
xpn_register_var_init_pdouble( var_list, pCh->pAtmos->dustr1,"pCh.pAtmos.dustr1",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pAtmos->dustr2,"pCh.pAtmos.dustr2",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pAtmos->dustr3,"pCh.pAtmos.dustr3",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pAtmos->dustr4,"pCh.pAtmos.dustr4",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pAtmos->dustr5,"pCh.pAtmos.dustr5",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fUsedRootWeight,"pCh.pCProfile.fUsedRootWeight",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fUsedLeafWeight,"pCh.pCProfile.fUsedLeafWeight",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fUsedBranchWeight,"pCh.pCProfile.fUsedBranchWeight",0.0);\
xpn_register_var_init_pdouble( var_list, pCh->pCProfile->fUsedStemWeight,"pCh.pCProfile.fUsedStemWeight",0.0);


