#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='leachn'


SOURCE_FILES=  [
                 'miner.c',
                 'denit.c',
                 'hydro.c',
                 'nitrification.c',
                 'plant.c',
                 'stickstoff_load.c',
                 'stickstoff_util.c',
                 'transpn.c',
                 'water_flow_hutson.c',
                 'transpn_register_modul.c'
                ]

def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_STD,
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_STD,
                install_path    = bld.env.INSTALL_MODELS
                )
