#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='ceres'


SOURCE_FILES=  [
                 'ceres.c',
                 'ceres_phenology.c',
                 'ceres_biomass_growth.c',
                 'ceres_canopy_formation.c',
                 'ceres_nitrogen.c',
                 'ceres_photosynthesis.c',
                 'ceres_transpiration.c',
                 'ceres_register_modul.c'
                ]


def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_CLASS,                
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_CLASS,
                install_path    = bld.env.INSTALL_MODELS
                )
