#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='treemix'


SOURCE_FILES=  [
                 'BiomassGrowth.c',
                 'CanopyFormation.c',
                 'CanopyPhotosynthesis.c',
                 'Initialization.c',
                 'libtreemix.c',
                 'libtreemix_register_modul.c',
                 'NitrogenDemand.c',
                 'NitrogenMineralisation.c',
                 'NitrogenNitrification.c',
                 'NitrogenUptake.c',
                 'Phenology.c',
                 'Senescence.c',
                 'Tools.c',
                 'Transpiration.c',
      		 'RootLengthGrowth.c'
                ]

     
def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_STD,                
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_STD,
                install_path    = bld.env.INSTALL_MODELS
                )
