#! /usr/bin/env python
# encoding: utf-8
# Christian Klein, 2012


LIBNAME='hpm'


SOURCE_FILES=  [
                 'hpm.c',
                 'hpm_albedo.c',
                 'hpm_evapotranspiration.c',
                 'hpm_growth.c',
                 'hpm_ini.c',
                 'hpm_math.c',
                 'hpm_nitrogen.c',
                 'hpm_photosynthesis.c',
                 'hpm_register_modul.c',
                 'hpm_root.c',
                 'hpm_water.c',
                 'hpm_harvest.c',
                 'hpm_animal.c'
                ]

        
def options(opt):
        pass

def configure(conf):
        pass

def build(bld):
    lib = bld(
                features        = 'c cshlib',
                source          = SOURCE_FILES,
                uselib          = bld.env.USELIB_STD,
                use             = bld.env.USE_STD,                
                target          = LIBNAME,
                includes        = bld.env.INCLUDES_STD,
                install_path    = bld.env.INSTALL_MODELS
                )
